name: Build Windows Only

on:
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Restore bridge files
        uses: actions/download-artifact@master
        with:
          name: bridge-artifact
          path: ./
        continue-on-error: true

      - uses: ./.github/workflows/flutter-build.yml
        with:
          upload-artifact: true
          upload-tag: "manual"
