name: Build Windows Only

on:
  workflow_dispatch:

env:
  RUST_VERSION: "1.75"
  LLVM_VERSION: "15.0.6"
  FLUTTER_VERSION: "3.24.5"
  VCPKG_COMMIT_ID: "120deac3062162151622ca4860575a33844ba10b"
  VERSION: "1.4.6"

jobs:
  generate-bridge:
    uses: ./.github/workflows/bridge.yml

  build-windows:
    needs: generate-bridge
    runs-on: windows-2022
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Restore bridge files
        uses: actions/download-artifact@master
        with:
          name: bridge-artifact
          path: ./

      - name: Install LLVM
        uses: KyleMayes/install-llvm-action@v1
        with:
          version: ${{ env.LLVM_VERSION }}

      - name: Install Flutter
        uses: subosito/flutter-action@v2.12.0
        with:
          channel: stable
          flutter-version: ${{ env.FLUTTER_VERSION }}

      - name: Install Rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env.RUST_VERSION }}
          targets: x86_64-pc-windows-msvc

      - uses: Swatinem/rust-cache@v2

      - name: Setup vcpkg
        uses: lukka/run-vcpkg@v11
        with:
          vcpkgDirectory: C:\vcpkg
          vcpkgGitCommitId: ${{ env.VCPKG_COMMIT_ID }}

      - name: Install vcpkg dependencies
        run: |
          C:\vcpkg\vcpkg install --classic --triplet x64-windows-static libvpx libyuv opus aom
        env:
          VCPKG_DEFAULT_TRIPLET: x64-windows-static
          VCPKG_ROOT: C:\vcpkg

      - name: Build Rust
        run: cargo build --release
        env:
          VCPKG_ROOT: C:\vcpkg

      - name: Flutter pub get
        run: flutter pub get
        working-directory: flutter

      - name: Build Flutter Windows
        run: flutter build windows --release
        working-directory: flutter

      - name: Copy librustdesk.dll
        run: |
          copy target\release\librustdesk.dll flutter\build\windows\x64\runner\Release\

      - name: Install NSIS
        run: |
          Invoke-WebRequest -Uri "https://sourceforge.net/projects/nsis/files/NSIS%203/3.09/nsis-3.09-setup.exe/download" -OutFile "$env:TEMP\nsis-setup.exe" -UserAgent "wget"
          Start-Process -Wait "$env:TEMP\nsis-setup.exe" -ArgumentList '/S'
          echo "C:\Program Files (x86)\NSIS" >> $env:GITHUB_PATH

      - name: Build installer
        run: |
          makensis /DVERSION=${{ env.VERSION }} res\setup.nsi

      - name: Upload installer
        uses: actions/upload-artifact@v4
        with:
          name: rustdesk-${{ env.VERSION }}-windows-installer
          path: rustdesk-*.exe
